import type { Locale } from '@/lib/seo';

export const homeContent = {
  fr: {
    kicker: 'Pentest web & API // France et remote',
    titleLead: 'SÉCURISEZ VOTRE',
    titleAccent: 'SAAS AVANT LA MISE EN PRODUCTION.',
    intro: 'J’identifie les chemins d’attaque exploitables dans vos applications et API, puis je livre un plan de correction priorisé que vos équipes peuvent appliquer.',
    primaryCta: 'Parler de votre audit', secondaryCta: 'Voir une réalisation', proofLabel: 'Signaux vérifiables',
    projectKicker: 'Étude de cas // Produit de cybersécurité', projectTitle: 'PRISMASEC : DE L’ACTIF VÉRIFIÉ AU RETEST.',
    projectText: 'Une plateforme CTEM conçue pour relier surface d’attaque, validation contrôlée, priorisation, remédiation et rapports sans perdre la frontière d’autorisation.',
    projectRole: 'Fondateur, CEO & Lead Engineer',
    projectEvidence: ['Architecture Next.js + Rust cloisonnée', 'Contrôles de vérification et de consentement', 'Livraison Kubernetes pilotée par GitOps'],
    projectCta: 'Lire l’étude de cas', servicesKicker: 'Services // Périmètres d’intervention', servicesTitle: 'DES AUDITS QUI DÉBLOQUENT L’ACTION.',
    servicesText: 'Chaque mission part d’un périmètre autorisé, valide des scénarios réalistes et se termine par des décisions de remédiation claires.',
    serviceCta: 'Cadrer cet audit', allServices: 'Voir tous les services', processKicker: 'Méthode // Du besoin au retest', processTitle: 'UN DÉROULÉ LISIBLE POUR VOS ÉQUIPES.',
    articlesKicker: 'Guides & recherche // Partage public', articlesTitle: 'DES MÉTHODES QUE VOUS POUVEZ ÉVALUER.',
    articlesText: 'Guides opérationnels, recherche applicative et write-ups pour rendre le raisonnement technique vérifiable.', readArticle: 'Lire', allArticles: 'Explorer les articles',
    aboutKicker: 'À propos // Opérateur', aboutTitle: 'OFFENSIF DANS LA MÉTHODE. PRAGMATIQUE DANS LA RESTITUTION.',
    aboutParagraphs: ['Pentester freelance et fondateur de PrismaSec, je travaille à l’intersection de la sécurité applicative, des API et de l’ingénierie bas niveau.', 'Formé à l’École 42, j’utilise la compréhension des systèmes, l’automatisation offensive et la documentation pour transformer une preuve technique en action compréhensible par les équipes qui corrigent.'],
    foundations: 'Fondations techniques', foundationItems: ['Sécurité web, API et logique métier', 'C, assembleur et compréhension système', 'Outillage offensif et automatisation'],
    finalTitle: 'UNE SURFACE À ÉVALUER AVANT VOTRE PROCHAINE ÉTAPE ?', finalText: 'Décrivez l’application, l’API ou l’environnement concerné. Le premier échange sert à vérifier l’adéquation et à préparer un périmètre utile.', finalCta: 'Demander un cadrage',
  },
  en: {
    kicker: 'Web & API pentesting // France and remote', titleLead: 'SECURE YOUR', titleAccent: 'SAAS BEFORE IT SHIPS.',
    intro: 'I identify exploitable attack paths in your applications and APIs, then deliver a prioritized remediation plan your team can act on.',
    primaryCta: 'Discuss your assessment', secondaryCta: 'View selected work', proofLabel: 'Verifiable signals',
    projectKicker: 'Case study // Cybersecurity product', projectTitle: 'PRISMASEC: FROM VERIFIED ASSET TO RETEST.',
    projectText: 'A CTEM platform designed to connect attack surface, controlled validation, prioritization, remediation, and reporting without losing the authorization boundary.',
    projectRole: 'Founder, CEO & Lead Engineer', projectEvidence: ['Separated Next.js + Rust architecture', 'Verification and consent controls', 'GitOps-driven Kubernetes delivery'],
    projectCta: 'Read the case study', servicesKicker: 'Services // Assessment surfaces', servicesTitle: 'ASSESSMENTS THAT UNBLOCK ACTION.',
    servicesText: 'Every engagement starts with authorized scope, validates realistic scenarios, and ends with clear remediation decisions.',
    serviceCta: 'Scope this assessment', allServices: 'View all services', processKicker: 'Method // From need to retest', processTitle: 'A CLEAR PROCESS FOR YOUR TEAM.',
    articlesKicker: 'Guides & research // Public work', articlesTitle: 'METHODS YOU CAN EVALUATE.', articlesText: 'Operational guides, application-security research, and write-ups that make the technical reasoning visible.', readArticle: 'Read', allArticles: 'Explore the articles',
    aboutKicker: 'About // Operator', aboutTitle: 'OFFENSIVE IN METHOD. PRAGMATIC IN DELIVERY.',
    aboutParagraphs: ['I am a freelance pentester and PrismaSec founder working across application security, APIs, and low-level engineering.', 'Trained at École 42, I use systems knowledge, offensive automation, and clear documentation to turn technical evidence into action for the teams responsible for fixing it.'],
    foundations: 'Technical foundations', foundationItems: ['Web, API, and business-logic security', 'C, assembly, and systems knowledge', 'Offensive tooling and automation'],
    finalTitle: 'A SURFACE TO ASSESS BEFORE YOUR NEXT MILESTONE?', finalText: 'Describe the application, API, or environment. The first conversation confirms fit and prepares a useful scope.', finalCta: 'Request scoping',
  },
} satisfies Record<Locale, Record<string, string | readonly string[]>>;
